##########################################
# Chatr Search - Clean SearXNG Settings  #
##########################################

general:
  debug: false
  instance_name: "Chatr Search"
  enable_metrics: false
  public_instance: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "replace_with_strong_key"
  allow_list: ["*"]
  rate_limit: 0

search:
  default_lang: "en"
  safe_search: 0
  autocomplete: "google"
  formats:
    - html
    - json
  deduplicate: true

ui:
  theme: simple
  query_in_title: true
  show_engine_name: false

engines:
  - name: google
    engine: google
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    disabled: false

  - name: bing
    engine: bing
    disabled: true

  - name: wikipedia
    engine: wikipedia
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    disabled: false

  - name: qwant
    engine: qwant
    disabled: false

outgoing:
  request_timeout: 4.0
  max_retry: 1
  pool_connections: 50
  pool_maxsize: 50
