use_default_settings: false

server:
  secret_key: "CHATR-INDIA-"20251201-144536""
  public_instance: true
  allow_public_api: true
  image_proxy: true

search:
  default_lang: "en-IN"
  default_locale: "IN"
  country: "IN"

ui:
  query_in_title: true
  infinite_scroll: true

output_formats:
  json: true

# --- CHATR JSON API ENABLED ---
allowed_formats:
  - html
  - json
  - csv

result_formats:
  json:
    mimetype: application/json
    batch: true
    http_headers:
      Content-Type: application/json
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, OPTIONS"
      Access-Control-Allow-Headers: "*"

engines:
  - name: json
    engine: JsonEngine
    disabled: false
